version: '3.4'

services:
  themanager:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    volumes:
      - /docker/datamalgamation/data/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - /docker/datamalgamation/data/ASP.NET/Https:/root/.aspnet/https:ro
      - /root/certs:/root/certs/

  thecollector:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "9200:80"
    volumes:
      - /docker/datamalgamation/data/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - /docker/datamalgamation/data/ASP.NET/Https:/root/.aspnet/https:ro
      - /root/certs:/root/certs/

  theportainer:    
    ports:
      - "9300:9000"
      - "8300:8000"    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  graylog:
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI="http://0.0.0.0:9000/"
    ports:
      - "9000:9000"
      - "12201:12201"
      - "1514:1514"

  elasticsearch:
    environment:
      - "http.host=0.0.0.0"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

volumes:
  portainer_data:  