version: '3.4'

services:
  themanager:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  thecollector:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  thelogger:
    environment:
      - GRAYLOG2_PASSWORD=graylog
    ports:
      - "9000:9000"
      - "12201:12201"
    volumes:
      - ${APPDATA}/graylog2/data:/var/opt/graylog2/data
      - ${APPDATA}/graylog2/logs:/var/log/graylog2