version: '3.4'

services:
  themanager:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    volumes:
      - /docker/datamalgamation/data/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - /docker/datamalgamation/data/ASP.NET/Https:/root/.aspnet/https:ro
      - /root/certs:/root/certs/

  thecollector:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "9200:80"
    volumes:
      - /docker/datamalgamation/data/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - /docker/datamalgamation/data/ASP.NET/Https:/root/.aspnet/https:ro
      - /root/certs:/root/certs/

  thelogger:
    environment:
      - GRAYLOG2_PASSWORD=graylog
    ports:
      - "9000:9000"
      - "12201:12201"
    volumes:
      - /docker/datamalgamation/data/graylog2/data:/var/opt/graylog2/data
      - /docker/datamalgamation/data/graylog2/logs:/var/log/graylog2
      - /root/certs:/root/certs/

  theportainer:    
    ports:
      - "9300:9000"
      - "8300:8000"    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:  